// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwkqiVyMvzqfSW1BMtIzPT9A4dK2VrR9g',
    appId: '1:1082954968772:web:c6822d69742edfbd47e391',
    messagingSenderId: '1082954968772',
    projectId: 'universealert-1345f',
    authDomain: 'universealert-1345f.firebaseapp.com',
    storageBucket: 'universealert-1345f.appspot.com',
    measurementId: 'G-R8LJ4J5MV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH65csmjInrhy-oq4ean7TaavvCTLIEHk',
    appId: '1:1082954968772:android:de5c0573338892ef47e391',
    messagingSenderId: '1082954968772',
    projectId: 'universealert-1345f',
    storageBucket: 'universealert-1345f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmuU0GtCaF4PcjzELj7JBii9eripRMdAU',
    appId: '1:1082954968772:ios:521fa09f45f5abae47e391',
    messagingSenderId: '1082954968772',
    projectId: 'universealert-1345f',
    storageBucket: 'universealert-1345f.appspot.com',
    iosBundleId: 'com.example.moyo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmuU0GtCaF4PcjzELj7JBii9eripRMdAU',
    appId: '1:1082954968772:ios:521fa09f45f5abae47e391',
    messagingSenderId: '1082954968772',
    projectId: 'universealert-1345f',
    storageBucket: 'universealert-1345f.appspot.com',
    iosBundleId: 'com.example.moyo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwkqiVyMvzqfSW1BMtIzPT9A4dK2VrR9g',
    appId: '1:1082954968772:web:a4a4f987aab75c1447e391',
    messagingSenderId: '1082954968772',
    projectId: 'universealert-1345f',
    authDomain: 'universealert-1345f.firebaseapp.com',
    storageBucket: 'universealert-1345f.appspot.com',
    measurementId: 'G-9RKEZ171X2',
  );
}
